import type { OU, User, ApprovalDocument } from '../types/approval';
import { generateDefaultStampSvg } from './stampHelper';

export const INITIAL_OUS: OU[] = [
  { id: 'ou-1', name: '기관장실', code: 'HQ', description: '최고 결정권자 부서' },
  { id: 'ou-2', name: '사무국', code: 'EX', parentId: 'ou-1', description: '총괄 행정 및 사업 관리' },
  { id: 'ou-3', name: '지역복지1팀', code: 'CW1', parentId: 'ou-2', description: '지역사회 조직 및 주민 복지 서비스' },
  { id: 'ou-4', name: '사례관리2팀', code: 'CM2', parentId: 'ou-2', description: '취약계층 맞춤형 사례 관리' },
  { id: 'ou-5', name: '운영지원팀', code: 'OP', parentId: 'ou-2', description: '회계, 인사, 시설 관리' },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    name: '김관장',
    ouId: 'ou-1',
    ouName: '기관장실',
    role: 'DIRECTOR',
    jobTitle: '관장',
    email: 'director.kim@swcenter.or.kr',
    phone: '010-1234-5678',
    stampUrl: generateDefaultStampSvg('김관장'),
  },
  {
    id: 'u-2',
    name: '이국장',
    ouId: 'ou-2',
    ouName: '사무국',
    role: 'MIDDLE_MANAGER',
    jobTitle: '사무국장',
    email: 'director.lee@swcenter.or.kr',
    phone: '010-2345-6789',
    stampUrl: generateDefaultStampSvg('이국장'),
  },
  {
    id: 'u-3',
    name: '박팀장',
    ouId: 'ou-3',
    ouName: '지역복지1팀',
    role: 'MIDDLE_MANAGER',
    jobTitle: '팀장',
    email: 'team.park@swcenter.or.kr',
    phone: '010-3456-7890',
    stampUrl: generateDefaultStampSvg('박팀장'),
  },
  {
    id: 'u-4',
    name: '최사회',
    ouId: 'ou-3',
    ouName: '지역복지1팀',
    role: 'STAFF',
    jobTitle: '사회복지사',
    email: 'sw.choi@swcenter.or.kr',
    phone: '010-4567-8901',
    stampUrl: generateDefaultStampSvg('최사회'),
  },
  {
    id: 'u-5',
    name: '정복지',
    ouId: 'ou-4',
    ouName: '사례관리2팀',
    role: 'STAFF',
    jobTitle: '사회복지사',
    email: 'sw.jung@swcenter.or.kr',
    phone: '010-5678-9012',
    stampUrl: generateDefaultStampSvg('정복지'),
  },
  {
    id: 'u-6',
    name: '강행정',
    ouId: 'ou-5',
    ouName: '운영지원팀',
    role: 'STAFF',
    jobTitle: '행정원',
    email: 'admin.kang@swcenter.or.kr',
    phone: '010-6789-0123',
    stampUrl: generateDefaultStampSvg('강행정'),
  },
];

export const INITIAL_DOCUMENTS: ApprovalDocument[] = [
  {
    id: 'doc-1',
    documentNumber: 'SW-2026-001',
    category: 'LEAVE',
    title: '2026년 하계 연차 사용 신청서 (최사회)',
    drafterId: 'u-4',
    drafterName: '최사회',
    drafterOU: '지역복지1팀',
    drafterJobTitle: '사회복지사',
    createdAt: '2026-07-28 09:30',
    status: 'IN_PROGRESS',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-3',
        approverName: '박팀장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '팀장',
        status: 'APPROVED',
        comment: '일정 확인하였습니다. 휴가 잘 다녀오세요.',
        approvedAt: '2026-07-28 11:15',
        stampUrl: generateDefaultStampSvg('박팀장'),
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'PENDING',
      },
    ],
    formData: {
      leaveType: '연차',
      startDate: '2026-08-03',
      endDate: '2026-08-05',
      daysCount: 3,
      reason: '여름 휴가 및 자기개발을 위한 연차 사용',
      emergencyContact: '010-4567-8901',
    },
  },
  {
    id: 'doc-2',
    documentNumber: 'SW-2026-002',
    category: 'WORK_STATUS_2',
    title: '보수교육 관련 공가 신청 (근무상황부2)',
    drafterId: 'u-5',
    drafterName: '정복지',
    drafterOU: '사례관리2팀',
    drafterJobTitle: '사회복지사',
    createdAt: '2026-07-27 14:00',
    status: 'APPROVED',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-2',
        approverName: '이국장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '사무국장',
        status: 'APPROVED',
        comment: '공가 사유 타당함.',
        approvedAt: '2026-07-27 15:30',
        stampUrl: generateDefaultStampSvg('이국장'),
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'APPROVED',
        comment: '최종 승인합니다.',
        approvedAt: '2026-07-27 17:00',
        stampUrl: generateDefaultStampSvg('김관장'),
      },
    ],
    formData: {
      category: '공가',
      startDate: '2026-07-30',
      endDate: '2026-07-30',
      daysCount: 1,
      reason: '2026 사회복지사 보수교육 필수 이수 참석',
      attachmentName: '사회복지사_보수교육_참석확인증.pdf',
    },
  },
  {
    id: 'doc-3',
    documentNumber: 'SW-2026-003',
    category: 'BUSINESS_TRIP',
    title: '관악구 종합사회복지관 벤치마킹 관외출장 신청서',
    drafterId: 'u-4',
    drafterName: '최사회',
    drafterOU: '지역복지1팀',
    drafterJobTitle: '사회복지사',
    createdAt: '2026-07-29 10:00',
    status: 'PENDING',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-3',
        approverName: '박팀장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '팀장',
        status: 'PENDING',
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'PENDING',
      },
    ],
    formData: {
      tripType: '관외출장',
      destination: '관악구 종합사회복지관',
      address: '서울특별시 관악구 관악로 145',
      lat: 37.4782,
      lng: 126.9515,
      startDate: '2026-08-10',
      endDate: '2026-08-10',
      purpose: '선진 사회복지관 주민참여형 사례관리 모범사례 벤치마킹',
      transportation: '대중교통',
      budgetEstimate: 25000,
      notes: '출장 후 결과보고서 제출 예정',
    },
  },
  {
    id: 'doc-4',
    documentNumber: 'SW-2026-004',
    category: 'OVERTIME_ORDER',
    title: '지역사회 바자회 준비를 위한 시간외근무 명령서',
    drafterId: 'u-3',
    drafterName: '박팀장',
    drafterOU: '지역복지1팀',
    drafterJobTitle: '팀장',
    createdAt: '2026-07-25 16:00',
    status: 'APPROVED',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-2',
        approverName: '이국장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '사무국장',
        status: 'APPROVED',
        comment: '시간외 사전승인 조치함.',
        approvedAt: '2026-07-25 17:10',
        stampUrl: generateDefaultStampSvg('이국장'),
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'APPROVED',
        comment: '승인.',
        approvedAt: '2026-07-25 17:50',
        stampUrl: generateDefaultStampSvg('김관장'),
      },
    ],
    formData: {
      workDate: '2026-07-26',
      startTime: '18:00',
      endTime: '21:00',
      plannedHours: 3,
      reason: '2026 희망나눔 바자회 물품 분류 및 무대 세팅 사전 작업',
      workContent: '바자회 기부 물품 가격표 부착 및 행사장 안내판 설치',
    },
  },
  {
    id: 'doc-5',
    documentNumber: 'SW-2026-005',
    category: 'OVERTIME_CONFIRM',
    title: '시간외근무 실적 확인서 (바자회 준비 건)',
    drafterId: 'u-4',
    drafterName: '최사회',
    drafterOU: '지역복지1팀',
    drafterJobTitle: '사회복지사',
    createdAt: '2026-07-27 09:00',
    status: 'APPROVED',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-3',
        approverName: '박팀장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '팀장',
        status: 'APPROVED',
        comment: '실제 일치 확인',
        approvedAt: '2026-07-27 10:00',
        stampUrl: generateDefaultStampSvg('박팀장'),
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'APPROVED',
        comment: '수고 많았습니다.',
        approvedAt: '2026-07-27 11:30',
        stampUrl: generateDefaultStampSvg('김관장'),
      },
    ],
    formData: {
      linkedOrderId: 'doc-4',
      workDate: '2026-07-26',
      actualStartTime: '18:00',
      actualEndTime: '21:00',
      actualHours: 3,
      workDetailReport: '18:00~19:30 기부물품 150여 점 소독 및 가격표 배치 완료. 19:30~21:00 행사 무대 음향 점검 및 안전 가이드 설치 수행함.',
    },
  },
  {
    id: 'doc-6',
    documentNumber: 'SW-2026-006',
    category: 'EDUCATION_APPLY',
    title: '사회복지 사례관리 전문성 강화 과정 교육 신청서',
    drafterId: 'u-5',
    drafterName: '정복지',
    drafterOU: '사례관리2팀',
    drafterJobTitle: '사회복지사',
    createdAt: '2026-07-20 11:00',
    status: 'APPROVED',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-2',
        approverName: '이국장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '사무국장',
        status: 'APPROVED',
        approvedAt: '2026-07-20 14:00',
        stampUrl: generateDefaultStampSvg('이국장'),
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'APPROVED',
        approvedAt: '2026-07-20 16:30',
        stampUrl: generateDefaultStampSvg('김관장'),
      },
    ],
    formData: {
      title: '고위험 가구 심층 사례관리 실무 심화과정',
      institution: '한국사회복지사협회 교육원',
      category: '직무교육',
      startDate: '2026-07-23',
      endDate: '2026-07-24',
      fee: 120000,
      reason: '복신사례 대상자의 개입 전략 수립 능력 향상 및 자원 연계 기법 습득',
    },
  },
  {
    id: 'doc-7',
    documentNumber: 'SW-2026-007',
    category: 'EDUCATION_REPORT',
    title: '고위험 가구 심층 사례관리 교육 결과보고서',
    drafterId: 'u-5',
    drafterName: '정복지',
    drafterOU: '사례관리2팀',
    drafterJobTitle: '사회복지사',
    createdAt: '2026-07-26 10:00',
    status: 'IN_PROGRESS',
    approvalLine: [
      {
        step: 1,
        approverId: 'u-2',
        approverName: '이국장',
        approverRole: 'MIDDLE_MANAGER',
        approverJobTitle: '사무국장',
        status: 'APPROVED',
        comment: '팀 내 교육 내용 전달 회의 진행할 것.',
        approvedAt: '2026-07-26 15:00',
        stampUrl: generateDefaultStampSvg('이국장'),
      },
      {
        step: 2,
        approverId: 'u-1',
        approverName: '김관장',
        approverRole: 'DIRECTOR',
        approverJobTitle: '관장',
        status: 'PENDING',
      },
    ],
    formData: {
      linkedApplyId: 'doc-6',
      title: '고위험 가구 심층 사례관리 실무 심화과정',
      institution: '한국사회복지사협회 교육원',
      completedDate: '2026-07-24',
      summary: '1일차: 다중 위기 가구의 욕구 파악 및 동기강화 상담 기법. 2일차: 지역사회 복지 자원 맵핑 및 기관 간 협의체 구성 방안.',
      learnings: '사례관리 진행 시 초기 라포 형성 과정에서의 동기강화 면담 기법을 적용하여 8월 신규 사례 개입에 반영할 계획임.',
      attachmentName: '교육이수증_정복지.pdf',
    },
  },
];
